### ISSUE TITLE
OffsetFinder cannot find offset correct in LOL 5.4.15

### ISSUE THREAD

**Issue by morefreeze** [struz/LoL-Ability-Timers#3]
I debug it find it can find "SkingName = " string correctly(e.g. this address is 0xabcd), but FindReferenceToAddress cannot find the address(e.g. 0xabcd) correctly, so all thing after that can't run at all.
I have searched LOL.exe by bytewise and can't find the address(e.g. 0xabcd). I use this command in Unix `xxd -p Lol.exe | tr -d '\n' | grep -c 'abcd` and it will return the count of address. I try reverse the address to 0xcdab and still can't find it.
Do I miss something?

**Comment by struz** [comment]
Hey.

I haven't looked at the code in a while, it definitely shouldn't run on the
current patch without a lot of changes.

Sorry about that.

**Comment by morefreeze** [comment]
That's alright. Your code of injection I still can learn from.
